# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpecicalOne' do
   pod 'Firebase/Core'
   pod 'Firebase/Auth'
   pod 'Firebase/Database'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

end