export const AUTH_STATE_CHANGED = 'AUTH_STATE_CHANGED';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SAVE_USER = 'SAVE_USER';

export const CHECK_FRIEND_STATUS = 'CHECK_FRIEND_STATUS';
export const SET_FRIEND = 'SET_FRIEND';
export const SET_MY_CRUSH = 'SET_MY_CRUSH';
export const CANCEL_CURRENT_CRUSH = 'CANCEL_CURRENT_CRUSH';
export const CURRENT_CRUSH_AGREE_ME = 'CURRENT_CRUSH_AGREE_ME';

export const REMOVE_FRIEND_SHIP = 'REMOVE_FRIEND_SHIP';

//converstation

export const SET_CONVERSATION_PATH = 'SET_CONVERSATION_PATH';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';